# Generated by Django 3.0.6 on 2020-06-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_power', models.FloatField(blank=True, null=True)),
                ('reactive_power', models.FloatField(blank=True, null=True)),
                ('latest_status', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
